#!/usr/bin/env python

try:
    while True:
        line = raw_input()
        if line is None: break

        n = int(line)
        print '<div style="border:1px solid black">'
        for i in range(n):
            line = raw_input()
            print '<img src="' + line + '"/>'
        print '</div>'
except EOFError:
    pass
